(lang dune 3.0)

(name ocaml-rpc)

(generate_opam_files true)

(package
 (name ocaml-rpc)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
  (dune
   (>= 2.2))
  lwt
  octez-libs))
